### ISSUE TITLE
A error about retry downloading songs

### ISSUE THREAD

**Issue by yuanqiuye** [LoliLin/CloudMan#2]
for track in playlist_tracks:
         i += 1
         if track['id'] not in track_error:
            track_error[track['id']] = 0

        。。。

         status = check_retry_limit(track['id'],track_error)
            if status == 1:
              log.error(CANNOT download music: ' + track['name'])
              continue
            elif status == 2:
              log.warning('Retring redownload music: ' + track['name'])
              log.warning('Failed times: ' + str(track_error[track['id']]))`

         。。。

         except Exception as e:
            log.error('Caused an error ........ : ' + str(e))
            playlist_tracks.append(track)
            track_error[track['id']] += 1
            continue
在這一段迴圈中，修復了歌曲會無限制地重複下載的問題 （以上已修復）
1. 原代碼中的track_error的賦值有錯誤

**Comment by LynMoe** [comment]
非常抱歉不小心 unwatch 了这个项目导致看不到 issue 提醒

现在已经使用 Node.js 重构了一遍, 可以尝试一下
