### ISSUE TITLE
關於處理flac的奇怪error

### ISSUE THREAD

**Issue by yuanqiuye** [LoliLin/CloudMan#5]
> [2020-08-19T13:57:33.952Z] [INFO] [Track: 魔法の扉] Downloaded!
> [2020-08-19T13:57:33.953Z] [INFO] [Track: 魔法の扉] Start processing...
> [2020-08-19T13:57:34.350Z] [INFO] [Track: スラッグ溪谷の朝] Start downloading...
> [2020-08-19T13:57:34.601Z] [INFO] [Track: 魔法の扉] Success!
> [2020-08-19T13:57:40.381Z] [ERROR] Error: Timeout
> [2020-08-19T13:57:40.381Z] [WARN] [Track: 星をのんだ少年][Music file] 1 times failed. 3 times left.
> [2020-08-19T13:57:46.821Z] [INFO] [Track: スラッグ溪谷の朝] Downloaded!
> [2020-08-19T13:57:46.822Z] [INFO] [Track: スラッグ溪谷の朝] Start processing...
> [2020-08-19T13:57:47.190Z] [INFO] [Track: ゴンドアの思い出] Start downloading...
> [2020-08-19T13:57:47.390Z] [INFO] [Track: スラッグ溪谷の朝] Success!
> [2020-08-19T13:57:51.384Z] [INFO] [Track: ゴンドアの思い出] Downloaded!
> [2020-08-19T13:57:51.385Z] [INFO] [Track: ゴンドアの思い出] Start processing...
> [2020-08-19T13:57:51.738Z] [INFO] [Track: 失意のパズー] Start downloading...
> [2020-08-19T13:57:51.917Z] [INFO] [Track: ゴンドアの思い出] Success!
> [2020-08-19T13:57:58.905Z] [INFO] [Track: 失意のパズー] Downloaded!
> [2020-08-19T13:57:58.906Z] [INFO] [Track: 失意のパズー] Start processing...
> [2020-08-19T13:57:59.259Z] [INFO] [Track: ロボット兵(復活〜救出)] Start downloading...
> [2020-08-19T13:57:59.414Z] [INFO] [Track: 失意のパズー] Success!
> [2020-08-19T13:58:14.011Z] [ERROR] Error: Timeout
> [2020-08-19T13:58:14.012Z] [WARN] [Track: 空から降ってきた少女][Music file] 1 times failed. 3 times left.
> [2020-08-19T13:58:41.398Z] [ERROR] Error: Timeout
> [2020-08-19T13:58:41.398Z] [WARN] [Track: 星をのんだ少年][Music file] 2 times failed. 2 times left.
> Progress [===>------------------------------------] 117/1326 8% ETA 6304.6sinternal/fs/utils.js:269
>     throw err;
>     ^
> 
> Error: EPERM: operation not permitted, stat 'C:\Users\chenh\AppData\Local\Temp\CloudMan\6f\442502.flac'
>     at Object.statSync (fs.js:1016:3)
>     at b.d (D:\CloudMan\node_modules\node-downloader-helper\dist\index.js:1:12019)
>     at WriteStream.<anonymous> (D:\CloudMan\node_modules\node-downloader-helper\dist\index.js:1:8450)
>     at WriteStream.emit (events.js:315:20)
>     at internal/fs/streams.js:247:14
>     at FSReqCallback.oncomplete (fs.js:156:23) {
>   errno: -4048,
>   syscall: 'stat',
>   code: 'EPERM',
>   path: 'C:\\Users\\chenh\\AppData\\Local\\Temp\\CloudMan\\6f\\442502.flac'
> }

如上，442502 (魔法の扉)這首歌已經download成功，也已經從temp中移動到walkman了，但不知道為什麼又請求了原本temp的檔案位置，具體error點在source code的哪邊也找不出來QQ 而且只有flac格式的音樂會遇到這樣的問題，還沒開會員之前用mp3都好好的w，附上playlist的ID:767047470，感謝！

**Comment by yuanqiuye** [comment]
後來不斷測試後發現，只要每次都刪掉temp似乎就可以解決了，雖然是治標不治本的做法ww

**Comment by yuanqiuye** [comment]
@isXiaoLin 更新到最新版後還是老樣子QQ，我這次用了[longjohn](https://github.com/mattinsler/longjohn)來trace error，得到以下結果：

> [2020-08-30T14:19:14.066Z] [INFO] [Track: 流れ行く云] Downloaded!
> [2020-08-30T14:19:14.067Z] [INFO] [Track: 流れ行く云] Start processing...
> [2020-08-30T14:19:15.134Z] [INFO] [Track: 静かな想い] Start downloading...
> [2020-08-30T14:19:15.396Z] [ERROR] Error: Timeout
> [2020-08-30T14:19:15.398Z] [WARN] [Track: 波の魚のポニョ][Music file] 2 times failed. 2 times left.
> [2020-08-30T14:19:15.501Z] [INFO] [Track: 流れ行く云] Success!
> [2020-08-30T14:19:26.545Z] [INFO] [Track: 静かな想い] Downloaded!
> [2020-08-30T14:19:26.547Z] [INFO] [Track: 静かな想い] Start processing...
> [2020-08-30T14:19:28.062Z] [INFO] [Track: 雨の中で] Start downloading...
> [2020-08-30T14:19:28.085Z] [INFO] [Track: 静かな想い] Success!
> [2020-08-30T14:19:32.473Z] [ERROR] Error: Timeout
> [2020-08-30T14:19:32.474Z] [WARN] [Track: Time travel][Music file] 2 times failed. 2 times left.
> [2020-08-30T14:19:37.274Z] [INFO] [Track: 大掃除] Downloaded!
> [2020-08-30T14:19:37.275Z] [INFO] [Track: 大掃除] Start processing...
> [2020-08-30T14:19:38.479Z] [INFO] [Track: 大掃除] Success!
> [2020-08-30T14:19:39.312Z] [INFO] [Track: 虚栄と友情] Start downloading...
> [2020-08-30T14:19:39.659Z] [ERROR] Error: Timeout
> [2020-08-30T14:19:39.661Z] [WARN] [Track: A Little More][Music file] 3 times failed. 1 times left.
> [2020-08-30T14:19:40.778Z] [ERROR] Error: Timeout
> [2020-08-30T14:19:40.780Z] [WARN] [Track: 奇迹の山][Music file] 2 times failed. 2 times left.
> Progress [==>-------------------------------------] 93/1467 6% ETA 3127.6sError: ENOENT: no such file or directory, stat  
>  'C:\Users\chenh\AppData\Local\Temp\CloudMan\7f53a256-0e94-4ddd-a21e-04de0292a075\441532.flac'
>     at Object.statSync (fs.js:1016:3)
>     at b.d (D:\CloudMan\node_modules\node-downloader-helper\dist\index.js:1:12019)
>     at WriteStream.<anonymous> (D:\CloudMan\node_modules\node-downloader-helper\dist\index.js:1:8450)
>     at WriteStream.emit (events.js:315:20)
>     at internal/fs/streams.js:247:14
>     at FSReqCallback.oncomplete (fs.js:156:23)
> 
>     at WriteStream.close (internal/fs/streams.js:456:10)
>     at WriteStream.<anonymous> (D:\CloudMan\node_modules\node-downloader-helper\dist\index.js:1:8221)
>     at WriteStream.emit (events.js:327:22)
>     at finishMaybe (_stream_writable.js:639:14)
>     at _stream_writable.js:616:5
>     at WriteStream._final (internal/fs/streams.js:352:3)
>     at callFinal (_stream_writable.js:609:10)
> 
>     at b.f (D:\CloudMan\node_modules\node-downloader-helper\dist\index.js:1:7893)
>     at ClientRequest.<anonymous> (D:\CloudMan\node_modules\node-downloader-helper\dist\index.js:1:6650)
>     at ClientRequest.emit (events.js:315:20)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
>     at HTTPParser.execute (<anonymous>)
>     at Socket.socketOnData (_http_client.js:469:22)
> ---------------------------------------------
>     at ClientRequest.once (events.js:437:8)
>     at new ClientRequest (_http_client.js:194:10)
>     at Object.request (http.js:46:10)
>     at b.d (D:\CloudMan\node_modules\node-downloader-helper\dist\index.js:1:5891)
>     at D:\CloudMan\node_modules\node-downloader-helper\dist\index.js:1:3058
>     at new Promise (<anonymous>)
>     at b (D:\CloudMan\node_modules\node-downloader-helper\dist\index.js:1:2868)
>     at D:\CloudMan\modules\general.js:45:12
>     at new Promise (<anonymous>)

Track: 流れ行く云 (441532)
Playlist: 2315314297

我對JS的非同步處理不是很熟，所以解決不了w，而且根據實驗發現，`cm_trackDownloadConcurrency`越大，flac出錯記錄越高？一頭霧水QQ，感謝小霖！

**Comment by yuanqiuye** [comment]
後來自己用python生出一個音源從客戶端來的工具，算是暫時解決自己的問題了 
(Nodejs 下載總是迷之錯誤w) 感謝作者長久以來的幫忙！
[Python Local版 CloudMan](https://github.com/yuanqiuye/CloudMan_Local)

**Comment by LynMoe** [comment]
https://github.com/isXiaoLin/CloudMan/releases/tag/v0.7.0

在最新版本中更新了下载模块并且优化了点小细节，可以再尝试一下
